# image will be published to ghcr.io/<user>/blazox
name: blazox
# description will be included in the image's metadata
description: Blazox - A custom Bazzite-based OS with KDE Plasma.
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-deck
image-version: latest
# module configuration, executed in order
modules:
  - type: files
    files:
      - usr:
          /usr

  - type: rpm-ostree
    repos:
    install:
      # adicione pacotes extras aqui futuramente
    remove:

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.kde.krita
      remove:

  - type: signing
